# -*- coding: utf-8 -*-
"""Task04_SD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSV3tU8FNLmRCaEcHcq-p4P7lzEnOtkq
"""

# Sudoku Solver using Backtracking Algorithm

def print_board(board):
    print("\nSolved Sudoku Board:\n")
    for row in board:
        print(" ".join(str(num) for num in row))


def find_empty(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return i, j
    return None


def is_valid(board, num, pos):
    row, col = pos

    # Check row
    for j in range(9):
        if board[row][j] == num and j != col:
            return False

    # Check column
    for i in range(9):
        if board[i][col] == num and i != row:
            return False

    # Check 3x3 box
    box_x = col // 3
    box_y = row // 3

    for i in range(box_y * 3, box_y * 3 + 3):
        for j in range(box_x * 3, box_x * 3 + 3):
            if board[i][j] == num and (i, j) != pos:
                return False

    return True


def solve(board):
    find = find_empty(board)
    if not find:
        return True
    else:
        row, col = find

    for num in range(1, 10):
        if is_valid(board, num, (row, col)):
            board[row][col] = num

            if solve(board):
                return True

            board[row][col] = 0  # backtrack

    return False


def main():
    # Example Sudoku puzzle (0 represents empty cells)
    board = [
        [7, 8, 0, 4, 0, 0, 1, 2, 0],
        [6, 0, 0, 0, 7, 5, 0, 0, 9],
        [0, 0, 0, 6, 0, 1, 0, 7, 8],
        [0, 0, 7, 0, 4, 0, 2, 6, 0],
        [0, 0, 1, 0, 5, 0, 9, 3, 0],
        [9, 0, 4, 0, 6, 0, 0, 0, 5],
        [0, 7, 0, 3, 0, 0, 0, 1, 2],
        [1, 2, 0, 0, 0, 7, 4, 0, 0],
        [0, 4, 9, 2, 0, 6, 0, 0, 7]
    ]

    print("Unsolved Sudoku Board:\n")
    for row in board:
        print(" ".join(str(num) for num in row))

    if solve(board):
        print_board(board)
    else:
        print("No solution exists.")


if __name__ == "__main__":
    main()